


C_FILES= $(wildcard *.c file_handler/*c screens/*c sfx/*c shared/*c models/*c data_api/*c)

all:
	@echo ""
	gcc -I. $(C_FILES) -o program.exe
	@echo ""
	@echo "All files are compiled"
	@echo ""

	
	
