/*
 * LCD_private.h
 *
 * Created: 04/08/2024 10:17:33 ص
 *  Author: a24e4
 */ 


#ifndef LCD_PRIVATE_H_
#define LCD_PRIVATE_H_

//dimensions
#define HLCD_ROWS_NUMBER 2
#define HLCD_COL_NUMBER 16

//CGRAM
#define HLCD_TOTAL_PATTERNS_NO 8
#define HLCD_PATTERN_ROWS_NO   8

//time delay
#define HLCD_BEFORE_INIT_TIME_US 1000
#define HLCD_CLK_HIGH_LVL_TIME_US 1000
#define HLCD_TIME_BETWEEN_SEND_2_NIPPES_US 1000
#define HLCD_AUXILIARY_TIME_AFTER_SEND_CMD_US 1000

//Commands
#define HLCD_CLR_SCREEN_CMD() 0x01
#define HLCD_CLR_SCREEN_CMD_RS 0
#define HLCD_CLR_SCREEN_CMD_RW 0
#define HLCD_CLR_SCREEN_CMD_TIME_US 1530

#define HLCD_RETURN_HOME_CMD() 0x02
#define HLCD_RETURN_HOME_CMD_RS 0
#define HLCD_RETURN_HOME_CMD_RW 0
#define HLCD_RETURN_HOME_CMD_TIME_US 1530

#define HLCD_ENTRY_SET_MODE_CMD(ID,SH) (0b00000100|((ID)<<1)|((SH)<<0))
#define HLCD_ENTRY_SET_MODE_CMD_RS 0
#define HLCD_ENTRY_SET_MODE_CMD_RW 0
#define HLCD_ENTRY_SET_MODE_CMD_TIME_US 39

#define HLCD_DISPLAY_CONTROL_CMD(D,C,B) (0b00001000|((D)<<2)|((C)<<1)|((B)<<0))
#define HLCD_DISPLAY_CONTROL_CMD_RS 0
#define HLCD_DISPLAY_CONTROL_CMD_RW 0
#define HLCD_DISPLAY_CONTROL_CMD_TIME_US 0

#define HLCD_CURSOR_DISPLAY_SHIFT_CMD(SC,RL) (0b00010000|((SC)<<3)|((RL)<<2))
#define HLCD_CURSOR_DISPLAY_SHIFT_CMD_RS 0
#define HLCD_CURSOR_DISPLAY_SHIFT_CMD_RW 0
#define HLCD_CURSOR_DISPLAY_SHIFT_CMD_TIME_US 39

#define HLCD_FUNCTION_SET_CMD(DL,N,F) (0b00100000|((DL)<<4)|((N)<<3)|((F)<<2))
#define HLCD_FUNCTION_SET_CMD_RS 0
#define HLCD_FUNCTION_SET_CMD_RW 0
#define HLCD_FUNCTION_SET_CMD_TIME_US 39

#define HLCD_SET_CGRAM_ADDRESS_CMD( AC_6_BITS) (0b01000000|((AC_6_BITS)&0x3f))
#define HLCD_SET_CGRAM_ADDRESS_CMD_RS 0
#define HLCD_SET_CGRAM_ADDRESS_CMD_RW 0
#define HLCD_SET_CGRAM_ADDRESS_CMD_TIME_US 39

#define HLCD_SET_DDRAM_ADDRESS_CMD(AC_7_BITS) (0b10000000|((AC_7_BITS)&0x7f))
#define HLCD_SET_DDRAM_ADDRESS_CMD_RS 0
#define HLCD_SET_DDRAM_ADDRESS_CMD_RW 0
#define HLCD_SET_DDRAM_ADDRESS_CMD_TIME_US 39

#define HLCD_READ_BUSY_FLAG_AND_ADDRESS_CMD(BF,AC_7_BITS) (0x00 | ((AC_7_BITS)&0x7f) |((BF)<<7) )
#define HLCD_READ_BUSY_FLAG_AND_ADDRESS_CMD_RS 0
#define HLCD_READ_BUSY_FLAG_AND_ADDRESS_CMD_RW 1
#define HLCD_READ_BUSY_FLAG_AND_ADDRESS_CMD_TIME_US 0

#define HLCD_WRITE_DATA_TO_ADDRESS_CMD(D_8_BITS) (D_8_BITS)
#define HLCD_WRITE_DATA_TO_ADDRESS_CMD_RS 1
#define HLCD_WRITE_DATA_TO_ADDRESS_CMD_RW 0
#define HLCD_WRITE_DATA_TO_ADDRESS_CMD_TIME_US 43

#define HLCD_READ_DATA_FROM_RAM_CMD(D_8_BITS) (D_8_BITS)
#define HLCD_READ_DATA_FROM_RAM_CMD_RS 1
#define HLCD_READ_DATA_FROM_RAM_CMD_RW 1
#define HLCD_READ_DATA_FROM_RAM_CMD_TIME_US 43

//registers addresses
#define HLCD_1_LINE_DISPLAY_MODE_REG_ADDRESS_START 0x00
#define HLCD_1_LINE_DISPLAY_MODE_REG_ADDRESS_END 0x4f

#define HLCD_2_LINE_DISPLAY_MODE_REG_LINE_1_ADDRESS_START 0x00
#define HLCD_2_LINE_DISPLAY_MODE_REG_LINE_1_ADDRESS_END 0x27
#define HLCD_2_LINE_DISPLAY_MODE_REG_LINE_2_ADDRESS_START 0x40
#define HLCD_2_LINE_DISPLAY_MODE_REG_LINE_2_ADDRESS_END 0x67




#endif /* LCD_PRIVATE_H_ */