/*
 * LightingSensor_conf.h
 *
 * Created: 8/1/2022 
 *  Author: mohammed ramadan
 */
 
#ifndef HAL_LIGHTINGSENSOR_LIGHTINGSENSOR_CONF_H_
#define HAL_LIGHTINGSENSOR_LIGHTINGSENSOR_CONF_H_

/*select ADC channel
 *Options
 **CHANNEL_0
 **CHANNEL_1
 **CHANNEL_2
 **CHANNEL_3
 **CHANNEL_4
 **CHANNEL_5
 **CHANNEL_6
 **CHANNEL_7
 */
#define LIGHTING_SENSOR_CHANNEL CHANNEL_0
#endif  /*HAL_LIGHTINGSENSOR_LIGHTINGSENSOR_CONF_H_*/