/*
 * SPI_config.h
 *
 * Created: 16/08/2024 11:21:13 م
 *  Author: a24e4
 */ 


#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_



//SPI MODE
#define MSPI_SLAVE_MODE 0
#define MSPI_MASTER_MODE 1
#define MSPI_MODE MSPI_MASTER_MODE

///For more info about Clock Phase and Clock Polarity, see TABLE 59, PAGE 139

// Clock Phase
#define MSPI_CLOCK_PHASE_SAMPLE_AT_LEADING_SETUP_AT_TRAILLING 0
#define MSPI_CLOCK_PHASE_SETUP_AT_LEADING_SAMPLE_AT_TRAILLING 1
#define MSPI_CLOCK_PHASE_SELECT MSPI_CLOCK_PHASE_SAMPLE_AT_LEADING_SETUP_AT_TRAILLING

// Clock Polarity
#define MSPI_CLOCK_POLARITY_IDLE_WHEN_LOW  0
#define MSPI_CLOCK_POLARITY_IDLE_WHEN_HIGH 1
#define MSPI_CLOCK_POLARITY_SELECT MSPI_CLOCK_POLARITY_IDLE_WHEN_LOW

//Relationship Between SCK and the Oscillator Frequency
#define MSPI_PRESCALER_4  0
#define MSPI_PRESCALER_16 1
#define MSPI_PRESCALER_64 2
#define MSPI_PRESCALER_128 3
#define MSPI_PRESCALER_2 4
#define MSPI_PRESCALER_8 5
#define MSPI_PRESCALER_32 6
#define MSPI_PRESCALER_64 7
#define SPI_PRESCALER_SELECT MSPI_PRESCALER_16

//DATA ORDER
#define MSPI_DATA_ORDER_MSB_IS_FIRST 0
#define MSPI_DATA_ORDER_LSB_IS_FIRST 1
#define MSPI_DATA_ORDER_SELECT MSPI_DATA_ORDER_MSB_IS_FIRST

//Enable interrupt code if the mode is SLAVE (0, 1)
#define MSPI_ENABLE_INTERRUPT 0



#endif /* SPI_CONFIG_H_ */